chains:
    - type: cosmos
      value:
        key: rly
        chain-id: defund
        rpc-addr: http://localhost:26657
        account-prefix: defund
        keyring-backend: test
        gas-adjustment: 1.2
        gas-prices: 0.01ufetf
        debug: true
        timeout: 20s
        output-format: json
        sign-mode: direct
    - type: cosmos
      value:
        key: rly
        chain-id: osmo-test-4
        rpc-addr: http://143.198.139.33:26657
        account-prefix: osmo
        keyring-backend: test
        gas-adjustment: 1.2
        gas-prices: 0.01uosmo
        debug: true
        timeout: 20s
        output-format: json
        sign-mode: direct